# frozen_string_literal: true

ICON_SOURCE = YAML.safe_load(File.open(Rails.application.config.redmine_svg_icon_source))
PLUGIN_TEMPLATE = Rails.root.join 'lib/generators/redmine_plugin/templates/'

SOURCE = URI.parse('https://api.iconify.design/')

SVG_START = "<svg xmlns=\"http://www.w3.org/2000/svg\"><symbol viewBox=\"0 0 %d %d\" id=\"icon\">\n  "
SVG_END = "\n</symbol></svg>"

WARNING = "Do not edit this file directly. This file is generated automatically with 'rake icon:fetch'"

namespace :icon do
  desc 'Fetch svg icons from icon source website'
  task fetch: :environment  do
    http = Net::HTTP.new(SOURCE.host, SOURCE.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    ICON_SOURCE.each do |k, v|
      icons = {}
      dir = if k == 'plugin'
              PLUGIN_TEMPLATE
            else
              Rails.public_path.join 'icons'
            end

      v.each_value do |i|
        prefix = i['prefix']
        icons[prefix] ||= []
        icons[prefix] << i['name']
      end

      http.start do |h|
        icons.each do |prefix, icons|
          source = "/#{prefix}.json?icons=#{icons.join(',')}"
          req = Net::HTTP::Get.new(source)
          res = h.request(req)
          case res
          when Net::HTTPSuccess
            json = JSON.parse res.body
            json['icons'].each do |name, content|
              target = File.join(dir, "#{name}.svg")
              width  = content.key?('width')  ? content['width']  : '512'
              height = content.key?('height') ? content['height'] : '512'
              File.open(target, 'w') do |f|
                f.print "<!-- #{WARNING} -->\n"
                f.printf SVG_START, width, height
                f.print content['body']
                f.print SVG_END
              end
            end
          else
            puts 'failed!!'
          end
        end
      end

      next if k == 'plugin'

      target = File.join(Rails.application.config.redmine_svg_icon_map, "#{k}.yml")
      iconlist = v.transform_values {|e| "#{e['name']}.svg" }
      File.open(target, 'w') do |f|
        f.print "# #{WARNING} .\n\n"
        f.print YAML.dump(iconlist)
      end
    end
  end
end
